
kind: pipeline
name: default

steps:
  - name: docker-to-hub
    image: thegeeklab/drone-docker-buildx:latest
    privileged: true
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      build_args:
        - PROJECT_VERSION=custom
      repo: bonny1992/phantombot
      tags: latest
      platforms:
        - linux/amd64
  - name: docker-to-quay
    image: thegeeklab/drone-docker-buildx:latest
    privileged: true
    settings:
      username:
        from_secret: QUAY_USER
      password:
        from_secret: QUAY_PASS
      build_args:
        - PROJECT_VERSION=custom
      registry: quay.io
      repo: quay.io/bonny1992/phantombot
      tags: latest
      platforms:
        - linux/amd64
  - name: docker-to-ghcr
    image: thegeeklab/drone-docker-buildx:latest
    privileged: true
    settings:
      username:
        from_secret: GHCR_USER
      password:
        from_secret: GITHUB_TOKEN
      build_args:
        - PROJECT_VERSION=custom
      registry: ghcr.io
      repo: ghcr.io/bonny1992/phantombot
      tags: latest
      platforms:
        - linux/amd64
